version: 2
jobs:
 build:
   docker:
    - image: ubuntu:xenial
   steps:
     - checkout
     - run: |
         apt-get update \
         && apt-get install -y \
         build-essential debhelper \
         tcl8.6-dev autoconf \
         python3-dev python3-venv \
         dh-systemd libz-dev \
         git wget \
         devscripts 
     - run: |
        sh git clone --single-branch --branch master git@github.com:flightaware/piaware_builder.git /git/piaware_builder
     - run : |
        sh cd /git/piaware_builder/ && sensible-build.sh xenial
     - run: | 
        cd /git/piaware_builder/package-xenial && dpkg-buildpackage -b -uc -us

     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t flighttracking/flightaware:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push flighttracking/flightaware:$CIRCLE_BRANCH